In [1]:
import pandas as pd
import numpy as np
from processing_data import fix_columns

In [2]:
cine = pd.read_csv('cine.csv', encoding='utf-8')
cine = fix_columns(cine)
cine.head(2)

,cod_loc,idprovincia,iddepartamento,observaciones,categoria,provincia,departamento,localidad,nombre,direccion,...,informacion_adicional,latitud,longitud,tipolatitudlongitud,fuente,tipo_gestion,pantallas,butacas,espacio_incaa,anio_actualizacion
0,10049030,10,10049,NaN,Salas de cine,Catamarca,Capital,Catamarca,Cinemacenter,Intendente Mamerto Medina 220,...,NaN,-28.464737,-65.800675,Localización precisa,INCAA / SInCA,Privado comercial,5,743,NaN,2018
1,10091150,10,10091,NaN,Salas de cine,Catamarca,Santa Maria,Santa María,Centro Cultural San Agustín,San Martin 173,...,NaN,-26.693859,-66.049058,Localización precisa,INCAA / SInCA,Privado comercial,1,440,0,2018

In [63]:
cine.espacio_incaa.unique()

array([0, 1])

In [48]:
total['provincia_categoria'] = total['provincia'] + ' - ' + total['categoria']

In [49]:
total['provincia'].replace({
    'Neuquén\xa0': 'Neuquén',
    'Santa Fé': 'Santa Fe',
    'Tierra del Fuego': 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'
    }, inplace=True)

In [50]:
total_resumen_categoria = total.pivot_table(index='categoria', values ='idprovincia', aggfunc='count')
total_resumen_categoria = total_resumen_categoria.reset_index()
total_resumen_categoria['tipo_agrupacion'] = 'Categoría'
total_resumen_categoria.rename(columns={'categoria': 'descripcion', 'idprovincia': 'total'}, inplace=True)
total_resumen_categoria

                          descripcion  total tipo_agrupacion
0               Bibliotecas Populares   2017       Categoría
1  Espacios de Exhibición Patrimonial   1182       Categoría
2                       Salas de cine    329       Categoría

In [51]:
total_resumen_fuente = total.pivot_table(index='fuente', values ='idprovincia', aggfunc='count')
total_resumen_fuente = total_resumen_fuente.reset_index()
total_resumen_fuente['tipo_agrupacion'] = 'Fuente'
total_resumen_fuente.rename(columns={'fuente': 'descripcion', 'idprovincia': 'total'}, inplace=True)
total_resumen_fuente

                                          descripcion  total tipo_agrupacion
0                                CNMLH - Enlace SInCA      1          Fuente
1                    CNMLH - Ente Cultural de Tucumán      1          Fuente
2                                             CONABIP   2010          Fuente
3                                               DNPyM   1048          Fuente
4   Dirección Provincial de Patrimonio Cultural - ...      1          Fuente
5               Dirección de Cultura de Villa Allende      2          Fuente
6   Dirección de Cultura y de Educación de la Muni...      1          Fuente
7                                          Gob. Pcia.      1          Fuente
8                            Gobierno de la Provincia     14          Fuente
9     Gobierno de la Provincia de Chubut / SInCA 2013      3          Fuente
10                  Gobierno de la Provincia de Jujuy      4          Fuente
11               Gobierno de la Provincia de La Pampa      1          Fuente
12               Gobierno de la Provincia de La Rioja      1          Fuente
13                Gobierno de la Provincia de Mendoza      4          Fuente
14                Gobierno de la Provincia de Neuquén      1          Fuente
15                  Gobierno de la Provincia de Salta      1          Fuente
16               Gobierno de la Provincia de San Juan      3          Fuente
17                           Gobierno de la provincia      1          Fuente
18                                      INCAA / SInCA    329          Fuente
19                     Municipalidad de Puerto Madryn      2          Fuente
20  Municipalidad de Río Gallegos - Red de Ciudade...      4          Fuente
21  Municipalidad de Santa Fe - Red de Ciudades Cr...     37          Fuente
22                                                RCC     10          Fuente
23                                       RCC- Córdoba     31          Fuente
24           Red de Espacios Culturales Vicente López      4          Fuente
25                                              SInCA      1          Fuente
26                   Secretaria de Cultura Provincial      6          Fuente
27  Secretaria de Cultura del Municipio de Esteban...      1          Fuente
28                                               UNLA      1          Fuente
29  Área Gestión Cultural de la Municipalidad de C...      4          Fuente

In [52]:
total_resumen_prov_cat = total.pivot_table(index='provincia_categoria', values ='idprovincia', aggfunc='count')
total_resumen_prov_cat = total_resumen_prov_cat.reset_index()
total_resumen_prov_cat['tipo_agrupacion'] = 'Provincia y Categoría'
total_resumen_prov_cat.rename(columns={'provincia_categoria': 'descripcion', 'idprovincia': 'total'}, inplace=True)
total_resumen_prov_cat

,descripcion,total,tipo_agrupacion
0,Buenos Aires - Bibliotecas Populares,543,Provincia y Categoría
1,Buenos Aires - Espacios de Exhibición Patrimonial,152,Provincia y Categoría
2,Buenos Aires - Salas de cine,106,Provincia y Categoría
3,Catamarca - Bibliotecas Populares,38,Provincia y Categoría
4,Catamarca - Espacios de Exhibición Patrimonial,32,Provincia y Categoría
...,...,...,...
68,Tierra del Fuego - Salas de cine,3,Provincia y Categoría
69,"Tierra del Fuego, Antártida e Islas del Atlánt...",14,Provincia y Categoría
70,Tucumán - Bibliotecas Populares,37,Provincia y Categoría
71,Tucumán - Espacios de Exhibición Patrimonial,26,Provincia y Categoría
72,Tucumán - Salas de cine,8,Provincia y Categoría

In [53]:
total = pd.concat([total_resumen_fuente,total_resumen_categoria, total_resumen_prov_cat], axis = 0)
total

,descripcion,total,tipo_agrupacion
0,CNMLH - Enlace SInCA,1,Fuente
1,CNMLH - Ente Cultural de Tucumán,1,Fuente
2,CONABIP,2010,Fuente
3,DNPyM,1048,Fuente
4,Dirección Provincial de Patrimonio Cultural - ...,1,Fuente
...,...,...,...
68,Tierra del Fuego - Salas de cine,3,Provincia y Categoría
69,"Tierra del Fuego, Antártida e Islas del Atlánt...",14,Provincia y Categoría
70,Tucumán - Bibliotecas Populares,37,Provincia y Categoría
71,Tucumán - Espacios de Exhibición Patrimonial,26,Provincia y Categoría
72,Tucumán - Salas de cine,8,Provincia y Categoría

In [54]:
total = total[['tipo_agrupacion', 'descripcion', 'total']]
total

,tipo_agrupacion,descripcion,total
0,Fuente,CNMLH - Enlace SInCA,1
1,Fuente,CNMLH - Ente Cultural de Tucumán,1
2,Fuente,CONABIP,2010
3,Fuente,DNPyM,1048
4,Fuente,Dirección Provincial de Patrimonio Cultural - ...,1
...,...,...,...
68,Provincia y Categoría,Tierra del Fuego - Salas de cine,3
69,Provincia y Categoría,"Tierra del Fuego, Antártida e Islas del Atlánt...",14
70,Provincia y Categoría,Tucumán - Bibliotecas Populares,37
71,Provincia y Categoría,Tucumán - Espacios de Exhibición Patrimonial,26
72,Provincia y Categoría,Tucumán - Salas de cine,8

In [ ]:
tabla_cine = cine.pivot_table(index='provincia', values = ['pantallas', 'butacas', 'espacio_incaa'], aggfunc='sum')
tabla_cine.reset_index()

In [62]:
cine['espacio_incaa'] = cine['espacio_incaa'].apply(lambda x: 1 if x == 'SI' or x == 'si' else 0)

In [64]:
tabla_cine = cine.pivot_table(index='provincia', values = ['pantallas', 'butacas', 'espacio_incaa'], aggfunc='sum')
tabla_cine.reset_index()

                          provincia  butacas  espacio_incaa  pantallas
0                      Buenos Aires    93112             20        358
1                         Catamarca     3200              1         12
2                             Chaco     2469              1         14
3                            Chubut     2682              4         10
4   Ciudad Autónoma de Buenos Aires    31386              3        153
5                        Corrientes     3370              1         17
6                           Córdoba    20799              2        105
7                        Entre Ríos     4086              2         17
8                           Formosa     1184              1          4
9                             Jujuy     2277              2          5
10                         La Pampa     2071              2          6
11                         La Rioja     1477              1         10
12                          Mendoza    11116              2         47
13                         Misiones     2177              2         10
14                          Neuquén     3959              3         12
15                        Río Negro     2474              4         10
16                            Salta     4665              2         23
17                         San Juan     4617              2         22
18                         San Luis     2601              0         12
19                       Santa Cruz     1256              2          7
20                         Santa Fe    20131              3         79
21              Santiago del Estero     2928              1         11
22                 Tierra del Fuego     1445              0          6
23                          Tucumán     5161              2         24

In [29]:
len(total.provincia.unique())

24

In [20]:
recuento_total_categoria = total.pivot_table(index='categoria', values='idprovincia', aggfunc='count')
recuento_total_categoria.rename(columns={'idprovincia': 'total'}, inplace=True)
recuento_total_categoria.reset_index()

                            categoria  idprovincia
0               Bibliotecas Populares         2017
1  Espacios de Exhibición Patrimonial         1182
2                       Salas de cine          329

In [22]:
recuento_total_fuente = total.pivot_table(index='fuente', values='idprovincia', aggfunc='count')
recuento_total_fuente.rename(columns={'idprovincia': 'total'}, inplace=True)
recuento_total_fuente.reset_index()

                                               fuente  idprovincia
0                                CNMLH - Enlace SInCA            1
1                    CNMLH - Ente Cultural de Tucumán            1
2                                             CONABIP         2010
3                                               DNPyM         1048
4   Dirección Provincial de Patrimonio Cultural - ...            1
5               Dirección de Cultura de Villa Allende            2
6   Dirección de Cultura y de Educación de la Muni...            1
7                                          Gob. Pcia.            1
8                            Gobierno de la Provincia           14
9     Gobierno de la Provincia de Chubut / SInCA 2013            3
10                  Gobierno de la Provincia de Jujuy            4
11               Gobierno de la Provincia de La Pampa            1
12               Gobierno de la Provincia de La Rioja            1
13                Gobierno de la Provincia de Mendoza            4
14                Gobierno de la Provincia de Neuquén            1
15                  Gobierno de la Provincia de Salta            1
16               Gobierno de la Provincia de San Juan            3
17                           Gobierno de la provincia            1
18                                      INCAA / SInCA          329
19                     Municipalidad de Puerto Madryn            2
20  Municipalidad de Río Gallegos - Red de Ciudade...            4
21  Municipalidad de Santa Fe - Red de Ciudades Cr...           37
22                                                RCC           10
23                                       RCC- Córdoba           31
24           Red de Espacios Culturales Vicente López            4
25                                              SInCA            1
26                   Secretaria de Cultura Provincial            6
27  Secretaria de Cultura del Municipio de Esteban...            1
28                                               UNLA            1
29  Área Gestión Cultural de la Municipalidad de C...            4

In [23]:
recuento_total_prov_cat= total.pivot_table(index=['provincia', 'categoria'], values='idprovincia', aggfunc='count')
recuento_total_prov_cat.rename(columns={'idprovincia': 'total'}, inplace=True)
recuento_total_prov_cat.reset_index()

,provincia,categoria,idprovincia
0,Buenos Aires,Bibliotecas Populares,543
1,Buenos Aires,Espacios de Exhibición Patrimonial,152
2,Buenos Aires,Salas de cine,106
3,Catamarca,Bibliotecas Populares,38
4,Catamarca,Espacios de Exhibición Patrimonial,32
...,...,...,...
68,Tierra del Fuego,Salas de cine,3
69,"Tierra del Fuego, Antártida e Islas del Atlánt...",Espacios de Exhibición Patrimonial,14
70,Tucumán,Bibliotecas Populares,37
71,Tucumán,Espacios de Exhibición Patrimonial,26
72,Tucumán,Salas de cine,8

In [7]:
lista = ['Cod_Loc',
        'IdProvincia',
        'IdDepartamento',
        'Categoría',
        'Provincia',
        'Localidad',
        'Nombre',
        'Domicilio',
        'Piso',
        'CP',
        'Cod_tel',
        'Teléfono',
        'Mail',
        'Web',
        'Fuente']

In [9]:
lista_lower = ['cod_loc', 'idprovincia', 'iddepartamento', 'categoria', 'provincia', 'localidad', 'nombre', 'domicilio', 'cp', 'telefono', 'mail', 'web', 'fuente']
lista_lower

['cod_loc',
 'idprovincia',
 'iddepartamento',
 'categoria',
 'provincia',
 'localidad',
 'nombre',
 'domicilio',
 'cp',
 'telefono',
 'mail',
 'web',
 'fuente']

In [3]:
df_bib = pd.read_csv('categorias/bibliotecas-populares/2022-febrero/bibliotecas-populares-17-02-2022.csv', encoding='utf-8')
df_museos = pd.read_csv('categorias/museos/2022-febrero/museos-17-02-2022.csv', encoding='utf-8')
df_cines = pd.read_csv('categorias/salas-de-cine/2022-febrero/salas-de-cine-17-02-2022.csv', encoding='utf-8')

In [ ]:
df_bib_resumen = df_bib[['Cod_Loc',
                        'IdProvincia',
                        'IdDepartamento',
                        'Categoría',
                        'Provincia',
                        'Localidad',
                        'Nombre',
                        'Domicilio',
                        'Piso',
                        'CP',
                        'Cod_tel',
                        'Teléfono',
                        'Mail',
                        'Web',
                        'Fuente']]

# KeyError: "['categoría', 'domicilio', 'cod_tel', 'teléfono'] not in index"

In [ ]:
df_cines_resumen = df_cines[['Cod_Loc',
                            'IdProvincia',
                            'IdDepartamento',
                            'Categoría',
                            'Provincia',
                            'Localidad',
                            'Nombre',
                            'Dirección',
                            'Piso',
                            'CP',
                            'cod_area',
                            'Teléfono',
                            'Mail',
                            'Web',
                            'Fuente']]

In [ ]:
df_museos_resumen = df_museos[['Cod_Loc',
                            'IdProvincia',
                            'IdDepartamento',
                            'Observaciones',
                            'categoria',
                            'provincia',
                            'localidad',
                            'nombre',
                            'direccion',
                            'piso',
                            'CP',
                            'cod_area',
                            'telefono',
                            'Mail',
                            'Web',
                            'fuente']]

In [1]:
df_total = pd.concat([df_bib, df_cines, df_bib_resumen], axis=0)

NameError: name 'pd' is not defined

In [4]:
df_bib.head(2)

,Cod_Loc,IdProvincia,IdDepartamento,Observacion,Categoría,Subcategoria,Provincia,Departamento,Localidad,Nombre,...,Mail,Web,Información adicional,Latitud,Longitud,TipoLatitudLongitud,Fuente,Tipo_gestion,año_inicio,Año_actualizacion
0,70049060,70,70049,NaN,Bibliotecas Populares,NaN,San Juan,Iglesia,Rodeo,Biblioteca Popular Juan P. Garramuno,...,s/d,NaN,NaN,-30.209250,-69.130117,Localización precisa,CONABIP,Comunitaria,1930.0,2018
1,2000010,2,2000,NaN,Bibliotecas Populares,NaN,Ciudad Autónoma de Buenos Aires,Ciudad Autonoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Helena Larroque de Roffo,...,asociacionroffo@yahoo.com.ar,NaN,NaN,-34.598461,-58.494690,Localización precisa,CONABIP,Comunitaria,1916.0,2018

In [5]:
df_museos.head(2)

,Cod_Loc,IdProvincia,IdDepartamento,Observaciones,categoria,subcategoria,provincia,localidad,nombre,direccion,...,Mail,Web,Latitud,Longitud,TipoLatitudLongitud,Info_adicional,fuente,jurisdiccion,año_inauguracion,IDSInCA
0,6588100,6,6588,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,9 de Julio,Archivo Y Museo Histórico Gral. Julio De Vedia,Libertad 1191,...,archivoymuseo@yahoo.com.ar,www.portaldel9.com.ar,-35.441762,-60.887598,Localización precisa,NaN,DNPyM,Municipal,1920.0,300003
1,6077010,6,6077,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,Arrecifes,Museo Y Archivo Histórico De Arrecifes,Gerardo Risso y España,...,museoarrecifes@hotmail.com,NaN,-34.066970,-60.102555,Localización precisa,NaN,DNPyM,Municipal,1972.0,300037

In [6]:
df_cines.head(2)

,Cod_Loc,IdProvincia,IdDepartamento,Observaciones,Categoría,Provincia,Departamento,Localidad,Nombre,Dirección,...,Información adicional,Latitud,Longitud,TipoLatitudLongitud,Fuente,tipo_gestion,Pantallas,Butacas,espacio_INCAA,año_actualizacion
0,10049030,10,10049,NaN,Salas de cine,Catamarca,Capital,Catamarca,Cinemacenter,Intendente Mamerto Medina 220,...,NaN,-28.464737,-65.800675,Localización precisa,INCAA / SInCA,Privado comercial,5,743,NaN,2018
1,10091150,10,10091,NaN,Salas de cine,Catamarca,Santa Maria,Santa María,Centro Cultural San Agustín,San Martin 173,...,NaN,-26.693859,-66.049058,Localización precisa,INCAA / SInCA,Privado comercial,1,440,0,2018

In [6]:
list(df_bib.columns)

['Cod_Loc',
 'IdProvincia',
 'IdDepartamento',
 'Observacion',
 'Categoría',
 'Subcategoria',
 'Provincia',
 'Departamento',
 'Localidad',
 'Nombre',
 'Domicilio',
 'Piso',
 'CP',
 'Cod_tel',
 'Teléfono',
 'Mail',
 'Web',
 'Información adicional',
 'Latitud',
 'Longitud',
 'TipoLatitudLongitud',
 'Fuente',
 'Tipo_gestion',
 'año_inicio',
 'Año_actualizacion']

In [19]:
list(df_cines.columns)

['Cod_Loc',
 'IdProvincia',
 'IdDepartamento',
 'Observaciones',
 'Categoría',
 'Provincia',
 'Departamento',
 'Localidad',
 'Nombre',
 'Dirección',
 'Piso',
 'CP',
 'cod_area',
 'Teléfono',
 'Mail',
 'Web',
 'Información adicional',
 'Latitud',
 'Longitud',
 'TipoLatitudLongitud',
 'Fuente',
 'tipo_gestion',
 'Pantallas',
 'Butacas',
 'espacio_INCAA',
 'año_actualizacion']

In [20]:
list(df_museos.columns)

['Cod_Loc',
 'IdProvincia',
 'IdDepartamento',
 'Observaciones',
 'categoria',
 'subcategoria',
 'provincia',
 'localidad',
 'nombre',
 'direccion',
 'piso',
 'CP',
 'cod_area',
 'telefono',
 'Mail',
 'Web',
 'Latitud',
 'Longitud',
 'TipoLatitudLongitud',
 'Info_adicional',
 'fuente',
 'jurisdiccion',
 'año_inauguracion',
 'IDSInCA']